linters:
  - pycodestyle:
      config: .pycodestylerc
  - autopep8:
      config: .pycodestylerc
      line-range: [79, 100]
  - pydocstyle:
  - pylint:
  - whitespace:
      filefilter: ['+ *.py', '+ *.rst']
  - header:
      extra: []
      shebang: '#!/usr/bin/env python3'
  - yamllint:
  - rst-lint:
      filefilter: ['+ README.rst']
